project_id = "yufholjudwhxgznyyzax"

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.ai-coach]
verify_jwt = false

[functions.send-results]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.validate-discount]
verify_jwt = false

[functions.resolve-error]
verify_jwt = false

[functions.d-id-talk]
verify_jwt = false

[functions.audio-session]
verify_jwt = false

[functions.send-pause-email]
verify_jwt = false
